=== DiegoSanchezPiedra/edt/2ASIX/M04/A2_xml_valid/A2_activitat8/1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="agenda">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="propietari" maxOccurs="unbounded"> 
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nom" type="xs:string"/>
                            <xs:element name="email" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="contactes">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="contacte" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nom" type="xs:string" maxOccurs="1"/>
                                        <xs:element name="telefon" maxOccurs="1">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                    <xs:pattern value="[0-9]{9}"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="email" type="xs:string" maxOccurs="1"/> 
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== DiegoSanchezPiedra/edt/2ASIX/M04/A2_xml_valid/A2_activitat8/1.xml
<?xml version="1.0" encoding="UTF-8"?>

<agenda xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="1.xsd">
    <propietari>
        <nom>Eloy Albiach Forner</nom>
        <email>eloy.albiachgmail.com</email>
    </propietari>
    <contactes>
        <contacte>
            <nom>Anna Monson√≠s</nom>
            <telefon>633124751</telefon>
            <email>annamongmail.com</email>
        </contacte>
        <contacte>
            <nom>Jordi Ventura</nom>
            <telefon>93415223</telefon>
            <email>jordivxtec.cat</email>
        </contacte>
    </contactes>
</agenda>
